### ISSUE TITLE
docs(rxjs): add readme and jsdoc for the "Share" decorator

### ISSUE THREAD

**Issue by dmitry-stepanenko** [DmitryEfimenko/ngspot#14]
Great implementation of the `Share` decorator, stumbled upon it on stackoverflow, however it would be nice to have accompanying docs.

Also, [Installation](https://www.npmjs.com/package/@ngspot/rxjs#installation) section references another package

**Comment by DmitryEfimenko** [comment]
Thanks for reporting this. Docs are adjusted
