### ISSUE TITLE
Unable to import NgxErrorsModule - missing from ngx-errors lib

### ISSUE THREAD

**Issue by lhargil** [DmitryEfimenko/ngspot#15]
Based on the [ReadMe](https://github.com/DmitryEfimenko/ngspot/blob/main/packages/ngx-errors/package/README.md#usage), 

```typescript
import { NgxErrorsModule } from '@ngspot/ngx-errors';
```

the NgxErrorsModule should be imported into a parent module, e.g. app.module to start using it, but the `NgxErrorsModule` is not exported in v4 anymore. 

What is the new approach now in moving from v3 to v4? Is there any migration guidance I could take a look at?

**Comment by DmitryEfimenko** [comment]
Good catch. I'll update the README.

Please import `NGX_ERRORS_DECLARATIONS` instead:
```ts
import { NGX_ERRORS_DECLARATIONS } from '@ngspot/ngx-errors'
```
